// Bundle the entire backend into a single minified dist/server.js for PM2.
//
// Output: dist/server.js  (one file, no node_modules needed at runtime
//                          except for the small set of native deps below)
//          dist/package.json  (slim — only the externals as deps)
//
// Run:  npm run build
//
// Deploy:
//   scp -r dist/ vaultchat:~/vaultchat-api/
//   ssh vaultchat
//   cd ~/vaultchat-api && npm install && pm2 start server.js --name vaultchat-api

const esbuild = require('esbuild');
const fs = require('fs');
const path = require('path');

const outdir = path.join(__dirname, 'dist');
// Try to wipe dist for a clean build, but don't die if Windows has a
// file lock on it (PM2 / Explorer / antivirus often hold node_modules
// open). esbuild will overwrite server.js either way, and the runtime
// package.json regeneration below is idempotent.
if (fs.existsSync(outdir)) {
  try {
    fs.rmSync(outdir, { recursive: true, force: true });
  } catch (err) {
    if (err && err.code === 'EBUSY') {
      console.warn('[build] dist/ is locked — overwriting in place instead of wiping');
    } else {
      throw err;
    }
  }
}
fs.mkdirSync(outdir, { recursive: true });

// Packages that can't be bundled into a single file:
// - bcrypt: native .node binary
// - pg-native: optional native binding, often missing; treat as external so
//   the bundle doesn't try to resolve it at build time
// - bufferutil / utf-8-validate: optional Socket.IO/ws native deps,
//   fail-soft at runtime if missing
const EXTERNALS = [
  'bcrypt',
  'pg-native',
  'bufferutil',
  'utf-8-validate',
  // Sentry uses dynamic requires for its OpenTelemetry instrumentation
  // packages. Mark external so esbuild doesn't try to bundle every
  // optional integration (and so we can update Sentry without rebuilding).
  '@sentry/node',
  '@sentry/profiling-node',
  '@opentelemetry/api',
  '@opentelemetry/core',
];

esbuild
  .build({
    entryPoints: [path.join(__dirname, 'server.js')],
    bundle: true,
    // Minification disabled — esbuild's identifier-renaming has produced
    // "ReferenceError: c2 is not defined" style crashes when combined with
    // our external + dynamic-require deps (Sentry, pg, etc). Whitespace+syntax
    // minify is still on (keeps the file compact without risking the rewrite).
    minify: false,
    minifyWhitespace: true,
    minifySyntax: true,
    platform: 'node',
    target: 'node18',
    format: 'cjs',
    outfile: path.join(outdir, 'server.js'),
    logLevel: 'info',
    legalComments: 'none',
    external: EXTERNALS,
    banner: {
      js: '/* VaultChat backend bundle — generated by build.js. Do not edit. */',
    },
  })
  .then(() => {
    const stat = fs.statSync(path.join(outdir, 'server.js'));
    const kb = (stat.size / 1024).toFixed(1);
    console.log(`\nBundle written: dist/server.js (${kb} KB)`);

    // Slim runtime package.json — only what `npm install` actually needs
    // on the server, which is just the externals plus their versions
    // copied from the dev manifest.
    const pkg = require('./package.json');
    const runtimeDeps = {};
    for (const name of EXTERNALS) {
      if (pkg.dependencies && pkg.dependencies[name]) {
        runtimeDeps[name] = pkg.dependencies[name];
      }
    }
    const runtime = {
      name: pkg.name,
      version: pkg.version,
      private: true,
      main: 'server.js',
      engines: pkg.engines,
      scripts: {
        start: 'node server.js',
        'pm2:start': 'pm2 start server.js --name vaultchat-api',
        'pm2:reload': 'pm2 reload vaultchat-api',
        'pm2:logs': 'pm2 logs vaultchat-api',
      },
      dependencies: runtimeDeps,
    };
    fs.writeFileSync(
      path.join(outdir, 'package.json'),
      JSON.stringify(runtime, null, 2)
    );
    console.log('Runtime package.json written: dist/package.json');

    // Copy migrations so the server has them locally for the deploy step
    const migSrc = path.join(__dirname, 'migrations');
    const migDst = path.join(outdir, 'migrations');
    if (fs.existsSync(migSrc)) {
      fs.cpSync(migSrc, migDst, { recursive: true });
      console.log('Migrations copied: dist/migrations/');
    }

    // .env.example for reference on the server
    const envExSrc = path.join(__dirname, '.env.example');
    if (fs.existsSync(envExSrc)) {
      fs.copyFileSync(envExSrc, path.join(outdir, '.env.example'));
      console.log('.env.example copied: dist/.env.example');
    }
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
