// Bundle the entire backend into a single minified dist/server.js for PM2.
//
// Output: dist/server.js  (one file, no node_modules needed at runtime
//                          except for native/dynamic-require deps marked
//                          external below).
//
// Run:  npm run build

const esbuild = require('esbuild');
const fs = require('fs');
const path = require('path');

const outdir = path.join(__dirname, 'dist');
if (fs.existsSync(outdir)) {
  fs.rmSync(outdir, { recursive: true, force: true });
}
fs.mkdirSync(outdir, { recursive: true });

esbuild
  .build({
    entryPoints: [path.join(__dirname, 'server.js')],
    bundle: true,
    minify: true,
    platform: 'node',
    target: 'node18',
    format: 'cjs',
    outfile: path.join(outdir, 'server.js'),
    logLevel: 'info',
    legalComments: 'none',

    // These packages don't bundle cleanly because they load .proto / .json
    // files via dynamic require at runtime, or have optional native add-ons.
    // Keeping them external means dist/ needs a slim package.json + npm ci.
    // If you want a TRULY single file with no node_modules, you can try
    // removing this — firebase-admin will fail at startup with
    // "Cannot find module './XXX.json'" if so.
    external: [
      'firebase-admin',
      // ws optional native deps used by socket.io; they fail-soft if missing
      'bufferutil',
      'utf-8-validate',
    ],

    banner: {
      js: '/* VaultChat backend bundle — generated by build.js. Do not edit. */',
    },
  })
  .then(() => {
    const stat = fs.statSync(path.join(outdir, 'server.js'));
    const kb = (stat.size / 1024).toFixed(1);
    console.log(`\nBundle written: dist/server.js (${kb} KB)`);
    // Write a slim package.json for runtime install (only externals)
    const pkg = require('./package.json');
    const runtime = {
      name: pkg.name,
      version: pkg.version,
      private: true,
      main: 'server.js',
      engines: pkg.engines,
      scripts: { start: 'node server.js' },
      dependencies: {
        'firebase-admin': pkg.dependencies['firebase-admin'],
      },
    };
    fs.writeFileSync(
      path.join(outdir, 'package.json'),
      JSON.stringify(runtime, null, 2)
    );
    console.log('Runtime package.json written: dist/package.json');
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
