apiVersion: v1
kind: Service
metadata:
  name: go-api
  labels:
    {{- include "crazzychat.labels" . | nindent 4 }}
    app.kubernetes.io/component: go-api
spec:
  type: ClusterIP
  selector:
    {{- include "crazzychat.goApiSelector" . | nindent 4 }}
  ports:
    - name: http
      port: 4000
      targetPort: http
