package routes

import (
	"encoding/json"
	"os"
	"testing"
)

// Node is the rollback target for this backend, so both implementations of the
// flag channel must put the same device in the same bucket. If they diverge, a
// rollback silently re-shuffles every canary cohort — devices that had the
// feature lose it, devices that never did get it, and the "monotone dial"
// property that makes 1% -> 10% -> 25% safe is gone.
//
// Vectors are generated by the Node side:
//
//	cd vaultchat-backend && node lib/flagResolve.js --emit > __vectors__/flag-buckets.json
//
// Regenerating them to make this test pass is a decision, not a fix: it means
// every device's bucket moved.
func TestBucketParityWithNode(t *testing.T) {
	const path = "../../../vaultchat-backend/__vectors__/flag-buckets.json"
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Skipf("bucket vectors not present (%v) — run `node lib/flagResolve.js --emit`", err)
	}

	var doc struct {
		Buckets map[string]map[string]int `json:"buckets"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("bucket vectors are unreadable: %v", err)
	}
	if len(doc.Buckets) == 0 {
		t.Fatal("bucket vectors are empty")
	}

	checked := 0
	for key, devices := range doc.Buckets {
		for device, want := range devices {
			if got := bucketOf(key, device); got != want {
				t.Fatalf("bucket drift for key=%q device=%q: Go=%d Node=%d", key, device, got, want)
			}
			checked++
		}
	}
	if checked < 100 {
		t.Fatalf("only %d vectors checked — the fixture is too thin to catch drift", checked)
	}
}
