// lib/flagResolve.js — the remote feature-flag resolution rules, and nothing else.
//
// Dependency-free on purpose. These rules exist twice (here and in
// vaultchat-backend-go/internal/routes/config.go) because Node is the rollback
// target for Go, and a rollback that changed which devices are in a canary
// would be worse than no rollback at all — the same device must land in the
// same bucket whichever backend answers.
//
// The two implementations are pinned together by __vectors__/flag-buckets.json:
// this file generates it (`node lib/flagResolve.js --emit`) and the Go test
// TestBucketParityWithNode asserts against it. If either side's hashing drifts,
// that test fails rather than the fleet silently re-shuffling.

const crypto = require('crypto');

/**
 * Stable 0..99 for (key, device).
 *
 * The key is mixed in so a device is not correlated across flags — otherwise
 * every 1% canary would land on the same unlucky devices and one cohort would
 * absorb the risk of every experiment.
 *
 * The value depends on nothing but its inputs, which is what makes raising the
 * dial monotone: a device inside 10% is still inside 25%. It never churns.
 */
function bucketOf(key, deviceId) {
  // A caller we cannot bucket stably must not flap in and out of a partial
  // rollout on every request. 100 sits outside every percentage.
  if (!deviceId) return 100;
  return crypto.createHash('sha256').update(`${key}:${deviceId}`).digest().readUInt32BE(0) % 100;
}

/**
 * Resolve one row for one caller. Order is the contract:
 * kill → build floor → percentage.
 */
function resolve(row, deviceId, build) {
  if (row.killed) return false;                                   // outranks everything
  if (row.min_build != null && build < row.min_build) return false;
  if (row.rollout_pct <= 0) return false;
  if (row.rollout_pct >= 100) return true;
  return bucketOf(row.key, deviceId) < row.rollout_pct;
}

module.exports = { bucketOf, resolve };

// `node lib/flagResolve.js --emit > __vectors__/flag-buckets.json`
if (require.main === module && process.argv.includes('--emit')) {
  const keys = ['VB_SEAMLESS_RESUME', 'FLAG_A', 'FLAG_B'];
  const buckets = {};
  for (const k of keys) {
    buckets[k] = {};
    for (let i = 0; i < 200; i++) {
      const d = `device-${String(i).padStart(4, '0')}`;
      buckets[k][d] = bucketOf(k, d);
    }
  }
  buckets['VB_SEAMLESS_RESUME'][''] = bucketOf('VB_SEAMLESS_RESUME', '');
  process.stdout.write(JSON.stringify({ note: 'generated by lib/flagResolve.js --emit', buckets }, null, 0) + '\n');
}
