/**
 * withBackupLockdown — take VaultChat out of Android's cloud backup entirely.
 *
 * THE PROBLEM
 * -----------
 * `android:allowBackup` defaults to TRUE, and the Expo prebuild template emits
 * it explicitly as true. Nothing in this project narrowed it: there was no
 * `android:fullBackupContent`, no `android:dataExtractionRules`, and no backup
 * rules XML anywhere in the repo.
 *
 * With that default, a Google-mediated restore (new device, factory reset,
 * device-to-device transfer) reinstates the app's sandbox — which for VaultChat
 * means:
 *
 *   databases/   → vaultchat.db, the local message cache (plaintext today,
 *                  since VAULT_CACHE_ENCRYPTED is off), AND AsyncStorage's
 *                  RKStorage, which holds every per-attachment media key
 *                  (vc_mk_<attachmentId>)
 *   files/       → downloaded media, VaultBeam transfers, note attachments
 *   shared_prefs/→ expo-secure-store's encrypted preferences
 *
 * So "uninstall, reinstall" could hand chat content straight back, and that
 * content also rested in Google's backup infrastructure with no user awareness.
 * `adb backup` was a second route to the same data on debuggable builds.
 *
 * (SecureStore values do get copied, but their Android Keystore keys do not —
 * uninstall destroys those — so tokens and E2EE identity return as
 * undecryptable ciphertext. That is why a reinstall still required a login even
 * though message bodies came back: the bodies came from the restored PLAINTEXT
 * cache, not from re-decryption.)
 *
 * THE FIX
 * -------
 * Set `android:allowBackup="false"` and `android:hasFragileUserData="false"` on
 * <application>. This is the correct posture for a messaging app: the server is
 * the sync mechanism, so cloud backup adds exposure without adding recovery.
 * Users who want a restore point have the app's own encrypted backup
 * (lib/cloudBackup), which they control.
 *
 * `hasFragileUserData="false"` additionally means the OS never offers to keep
 * app data across an uninstall — the "keep app data" checkbox some launchers
 * show. Leaving it unset would let a user re-create the exact behaviour we are
 * removing.
 *
 * WHY THIS MUST BE A CONFIG PLUGIN
 * --------------------------------
 * /android is gitignored and regenerated by `expo prebuild --clean` on every EAS
 * build, so a hand-edited AndroidManifest.xml is silently discarded. Verify the
 * shipped artifact, not the source tree:
 *
 *   aapt2 dump xmltree app-release.apk --file AndroidManifest.xml | grep -i allowBackup
 *   → android:allowBackup(0x0101000c)=(type 0x12)0x0    // 0x0 == false
 *
 * IF BACKUP IS EVER WANTED BACK
 * -----------------------------
 * Do not simply flip this to true. Ship BOTH `backup_rules.xml` (API ≤ 30,
 * android:fullBackupContent) and `data_extraction_rules.xml` (API 31+,
 * android:dataExtractionRules) as explicit ALLOW-lists — Android picks a
 * different attribute per API level, so shipping one leaves the other range on
 * the permissive default. Any such list must exclude databases/, files/ and
 * shared_prefs/ in full.
 *
 * Run: expo prebuild --clean
 */
const { withAndroidManifest } = require('@expo/config-plugins');

module.exports = function withBackupLockdown(config) {
  return withAndroidManifest(config, (cfg) => {
    const app = cfg.modResults.manifest.application?.[0];
    if (!app) return cfg;   // nothing to harden; let the build proceed

    app.$ = app.$ || {};
    app.$['android:allowBackup'] = 'false';
    app.$['android:hasFragileUserData'] = 'false';

    // WIN THE MERGE, do not just state a preference.
    //
    // A LIBRARY can re-open this. react-native-compressor pulls in
    // TAndroidLame, whose manifest declares android:allowBackup="true", and the
    // merger refuses to guess between the two:
    //
    //   Manifest merger failed : Attribute application@allowBackup
    //   value=(false) from AndroidManifest.xml is also present at
    //   [com.github.kaushik-naik:TAndroidLame] value=(true)
    //
    // That failure is the GOOD outcome — it is loud. The dangerous version is a
    // merger that silently prefers the library and quietly restores backup of
    // the message cache and every per-attachment media key. tools:replace says
    // this app's value is deliberate and wins, so any future dependency that
    // ships the permissive default is overridden rather than obeyed.
    //
    // hasFragileUserData is listed too: it defaults to false, but a library
    // asserting true would keep app data across an uninstall — the same class
    // of leak by a different door.
    const tools = 'android:allowBackup,android:hasFragileUserData';
    app.$['tools:replace'] = app.$['tools:replace']
      ? Array.from(new Set([...String(app.$['tools:replace']).split(','), ...tools.split(',')]
          .map((s) => s.trim()).filter(Boolean))).join(',')
      : tools;

    // tools: is only a namespace if it is declared on <manifest>. Without this
    // the attribute above is an unknown attribute and the merge fails anyway.
    const manifest = cfg.modResults.manifest;
    manifest.$ = manifest.$ || {};
    if (!manifest.$['xmlns:tools']) {
      manifest.$['xmlns:tools'] = 'http://schemas.android.com/tools';
    }

    // These only have meaning while backup is enabled, and leaving a stale
    // reference behind would point at a rules file we do not ship.
    delete app.$['android:fullBackupContent'];
    delete app.$['android:dataExtractionRules'];

    return cfg;
  });
};
