// lib/finance/grid.selftest.ts — the finance grid has to fit the screen it is on.
//
//   npx tsx lib/finance/grid.selftest.ts
//
// Two kinds of check here.
//
// 1. The layout properties a device can contradict: a row of cells never
//    exceeds the width it was given, never goes negative, and never collapses
//    to something unreadable. These are the ones that catch a real regression.
//
// 2. Agreement with the Figma file. The 320 / 390 / 744 artboards in
//    N5Y6KcMUPA3LgtWjfHPctz were generated by running these exact functions, so
//    pinning their outputs here means changing a breakpoint in code without
//    reopening the design file fails loudly instead of silently drifting.

import { readFileSync } from 'fs';
import { join } from 'path';
import {
  contentWidth, tileColumns, quickActionColumns, heroStacks, columnWidth,
  FIN_GUTTER, FIN_GAP, QA_MIN_DP, QA_MIN_COLS, QA_MAX_COLS,
  FIN_CONTENT_MAX_DP, HERO_STACK_BELOW_DP,
} from './grid';

let failed = 0;
function A(ok: boolean, what: string): void {
  if (ok) { console.log('  ok   ' + what); return; }
  failed++;
  console.log('  FAIL ' + what);
}

console.log('\nVault Finance grid\n');

// Real windows, in dp. The two test phones are the ones that matter most.
const SCREENS: [number, string][] = [
  [320, 'smallest phone we support'],
  [360, 'Honor ELI-NX9 portrait'],
  [369, 'Honor, measured dp'],
  [390, 'reference phone'],
  [392, 'Redmi Note 8 Pro, measured dp'],
  [412, 'large phone'],
  [600, 'small tablet / sw600dp'],
  [744, 'tablet portrait'],
  [800, 'tablet'],
  [1280, 'tablet landscape'],
];

// ── 1. a row must never exceed the width it was given ────────────────
{
  for (const [w, name] of SCREENS) {
    const inner = contentWidth(w);

    const tc = tileColumns(w);
    const tw = columnWidth(inner, tc);
    A(tw > 0 && tw * tc + FIN_GAP * (tc - 1) <= inner,
      `1a. ${name} (${w}dp): ${tc} tiles of ${tw}dp fit inside ${inner}dp`);

    const qc = quickActionColumns(w);
    const qw = columnWidth(inner, qc);
    A(qw > 0 && qw * qc + FIN_GAP * (qc - 1) <= inner,
      `1b. ${name} (${w}dp): ${qc} actions of ${qw}dp fit inside ${inner}dp`);

    // ...and never refuse space that exists: one more column must NOT fit.
    if (qc < QA_MAX_COLS) {
      const next = qc + 1;
      A(columnWidth(inner, next) < QA_MIN_DP,
        `1c. ${name} (${w}dp): ${next} actions would be under ${QA_MIN_DP}dp, so ${qc} is right`);
    }
  }
}

// ── 2. quick-action tiles stay legible at every width ────────────────
{
  for (const [w, name] of SCREENS) {
    const qw = columnWidth(contentWidth(w), quickActionColumns(w));
    A(qw >= QA_MIN_DP - 1,   // -1 absorbs the floor()
      `2. ${name} (${w}dp): action tile ${qw}dp is at least the ${QA_MIN_DP}dp floor`);
  }
}

// ── 3. columns are clamped at both ends ──────────────────────────────
{
  for (const w of [200, 320, 390, 744, 1280, 4000]) {
    const qc = quickActionColumns(w);
    A(qc >= QA_MIN_COLS && qc <= QA_MAX_COLS, `3a. ${w}dp: ${qc} columns is inside [${QA_MIN_COLS}, ${QA_MAX_COLS}]`);
  }
  A(quickActionColumns(4000) === quickActionColumns(FIN_CONTENT_MAX_DP),
    '3b. past the content cap, extra window width adds no more columns');
}

// ── 4. degenerate inputs do not produce a broken layout ──────────────
{
  // Dimensions can report 0 mid-rotation; a NaN here would silently blank a screen.
  for (const bad of [0, -1, NaN, Infinity]) {
    A(contentWidth(bad) === 0, `4a. contentWidth(${bad}) is 0, not NaN`);
    A(quickActionColumns(bad) === QA_MIN_COLS, `4b. quickActionColumns(${bad}) falls back to ${QA_MIN_COLS}`);
    A(columnWidth(bad, 4) === 0, `4c. columnWidth(${bad}, 4) is 0, not negative`);
  }
  A(columnWidth(300, 0) === 0, '4d. zero columns is 0, not a divide-by-zero');
}

// ── 5. the money-wrapping rule that the 320dp artboard found ─────────
{
  A(heroStacks(320), '5a. 320dp stacks the hero, so ₹4,52,000 cannot break mid-number');
  A(!heroStacks(390), '5b. 390dp splits it side by side');
  A(heroStacks(HERO_STACK_BELOW_DP - 1) && !heroStacks(HERO_STACK_BELOW_DP),
    '5c. the stack threshold is exactly HERO_STACK_BELOW_DP');
}

// ── 6. agreement with the Figma artboards ────────────────────────────
// Changing a breakpoint without reopening the design file fails here.
{
  const BOARDS: [number, number, number, string][] = [
    // width, tileCols, quickActionCols, artboard name
    [320, 2, 3, 'Dashboard · 320dp · small phone'],
    [390, 2, 4, 'Dashboard · 390dp'],
    [744, 4, 6, 'Dashboard · 744dp · tablet'],
  ];
  for (const [w, tc, qc, board] of BOARDS) {
    A(tileColumns(w) === tc, `6a. ${board}: ${tc} tile columns`);
    A(quickActionColumns(w) === qc, `6b. ${board}: ${qc} quick-action columns`);
  }
  A(contentWidth(744) === FIN_CONTENT_MAX_DP - FIN_GUTTER * 2,
    '6c. the tablet board reads at the capped column width, not the full 744dp');
}

// ── 7. no finance screen has gone back to hardcoded device numbers ───
{
  const ROOT = join(__dirname, '..', '..');
  const FILES = [
    'app/finance/index.tsx',
    'components/finance/ui.tsx',
    'constants/financeTheme.ts',
  ];
  for (const f of FILES) {
    const src = readFileSync(join(ROOT, f), 'utf8');
    const code = src.split('\n').filter(l => !/^\s*(\/\/|\*|\/\*)/.test(l)).join('\n');

    // the specific device widths the brief calls out
    A(!/\b(?:360|375|390|393|411|412|414|428|1080|1920|2340)\b/.test(code),
      `7a. ${f} contains no hardcoded device dimension`);

    // the Platform.OS status-bar guess the header used to carry
    A(!/paddingTop:\s*Platform\.OS/.test(code),
      `7b. ${f} does not guess the status bar height from Platform.OS`);
  }

  // the dashboard must derive its grids, not count them out by hand.
  // Comments are stripped first — this file documents the value it removed.
  const dashSrc = readFileSync(join(ROOT, 'app/finance/index.tsx'), 'utf8');
  const dash = dashSrc.split('\n').filter(l => !/^\s*(\/\/|\*|\/\*)/.test(l)).join('\n');
  A(/quickActionColumns|ActionGrid/.test(dash), '7c. the dashboard derives its quick-action columns');
  A(!/width:\s*'22%'/.test(dash), '7d. ...and the fixed 22% action tile is gone');
}

// ── 8. every finance colour pair clears WCAG AA ──────────────────────
// The palette is read out of the source rather than imported, because
// constants/financeTheme.ts imports constants/theme.ts which imports
// react-native — not loadable under plain node. Parsing the literals keeps this
// check runnable in the same `tsx` pass as everything else.
{
  const ROOT = join(__dirname, '..', '..');
  const src = readFileSync(join(ROOT, 'constants/financeTheme.ts'), 'utf8');

  const P: Record<string, string> = {};
  for (const m of src.matchAll(/^\s{2}(\w+):\s*'(#[0-9A-Fa-f]{6})'/gm)) P[m[1]] = m[2];

  const lum = (h: string) => {
    const n = parseInt(h.slice(1), 16);
    const ch = [(n >> 16) & 255, (n >> 8) & 255, n & 255].map(v => {
      const c = v / 255;
      return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
    });
    return 0.2126 * ch[0] + 0.7152 * ch[1] + 0.0722 * ch[2];
  };
  const ratio = (a: string, b: string) => {
    const [x, y] = [lum(a), lum(b)].sort((p, q) => q - p);
    return (x + 0.05) / (y + 0.05);
  };

  // fg, bg, the AA bar, and what it is
  const PAIRS: [string, string, number, string][] = [
    ['text', 'cardSolid', 4.5, 'body text on a card'],
    ['text', 'bgTop', 4.5, 'body text on the ice ground (top)'],
    ['text', 'bgBottom', 4.5, 'body text on the ice ground (bottom)'],
    ['sub', 'cardSolid', 4.5, 'secondary text on a card'],
    ['sub', 'bgBottom', 4.5, 'secondary text on the ground'],
    ['faint', 'cardSolid', 4.5, 'placeholder / hint text'],
    ['good', 'cardSolid', 4.5, 'a gain figure on a card'],
    ['good', 'goodSoft', 4.5, 'a gain pill'],
    ['bad', 'cardSolid', 4.5, 'a loss figure on a card'],
    ['bad', 'badSoft', 4.5, 'an overdue pill'],
    ['warn', 'cardSolid', 4.5, 'a pending figure on a card'],
    ['warn', 'warnSoft', 4.5, 'a pending pill'],
    ['info', 'cardSolid', 4.5, 'an informational figure'],
    ['info', 'infoSoft', 4.5, 'an informational pill'],
    ['brandInk', 'brandSoft', 4.5, 'a label on a soft brand fill'],
    ['brandInk', 'cardSolid', 4.5, 'the selected segment label'],
    ['onBrand', 'brandDeep', 4.5, 'the primary button label'],
    ['onBrand', 'brandInk', 4.5, 'hero text at the darkest gradient stop'],
    ['sub', 'card2', 4.5, 'a completed pill'],
  ];

  for (const [fg, bg, bar, what] of PAIRS) {
    A(!!P[fg] && !!P[bg], `8a. both ${fg} and ${bg} were parsed out of the palette`);
    if (!P[fg] || !P[bg]) continue;
    const r = ratio(P[fg], P[bg]);
    A(r >= bar, `8b. ${what}: ${fg} on ${bg} is ${r.toFixed(2)}:1 (needs ${bar})`);
  }

  // The hero gradient runs brandInk → brandDeep → brand. White has to survive
  // the LIGHTEST stop, which is the one that would fail.
  A(ratio('#FFFFFF', P.brandDeep) >= 4.5,
    `8c. white on the hero's mid gradient stop is ${ratio('#FFFFFF', P.brandDeep).toFixed(2)}:1`);
}

// ── 9. StatTile keeps the flex that three screens depend on ──────────
// Dropping `flex: 1` from the tile style is invisible on the dashboard (where
// TileGrid gives each tile a fixed-width wrapper) and silently collapses the
// bare `tileRow` on reports / customer / chitti. It was removed once already.
{
  const ROOT = join(__dirname, '..', '..');
  const ui = readFileSync(join(ROOT, 'components/finance/ui.tsx'), 'utf8');
  const tileLine = ui.split('\n').find(l => /^\s{2}tile:\s*\{/.test(l)) ?? '';
  A(/flex:\s*1/.test(tileLine), '9a. the StatTile style still declares flex: 1');

  for (const f of ['app/finance/reports.tsx', 'app/finance/customer.tsx', 'app/finance/chitti/[id].tsx']) {
    const src = readFileSync(join(ROOT, f), 'utf8');
    A(/tileRow:\s*\{[^}]*flexDirection:\s*'row'/.test(src),
      `9b. ${f} still lays its tiles out in a row`);
  }
}

console.log(failed === 0 ? '\nAll good.\n' : `\n${failed} FAILED\n`);
process.exit(failed === 0 ? 0 : 1);
