// lib/finance/grid.selftest.ts — the finance grid has to fit the screen it is on.
//
//   npx tsx lib/finance/grid.selftest.ts
//
// Two kinds of check here.
//
// 1. The layout properties a device can contradict: a row of cells never
//    exceeds the width it was given, never goes negative, and never collapses
//    to something unreadable. These are the ones that catch a real regression.
//
// 2. Agreement with the Figma file. The 320 / 390 / 744 artboards in
//    N5Y6KcMUPA3LgtWjfHPctz were generated by running these exact functions, so
//    pinning their outputs here means changing a breakpoint in code without
//    reopening the design file fails loudly instead of silently drifting.

import { readFileSync } from 'fs';
import { join } from 'path';
import {
  contentWidth, tileColumns, quickActionColumns, heroStacks, columnWidth,
  FIN_GUTTER, FIN_GAP, QA_MIN_DP, QA_MIN_COLS, QA_MAX_COLS,
  FIN_CONTENT_MAX_DP, HERO_STACK_BELOW_DP,
} from './grid';

let failed = 0;
function A(ok: boolean, what: string): void {
  if (ok) { console.log('  ok   ' + what); return; }
  failed++;
  console.log('  FAIL ' + what);
}

console.log('\nVault Finance grid\n');

// Real windows, in dp. The two test phones are the ones that matter most.
const SCREENS: [number, string][] = [
  [320, 'smallest phone we support'],
  [360, 'Honor ELI-NX9 portrait'],
  [369, 'Honor, measured dp'],
  [390, 'reference phone'],
  [392, 'Redmi Note 8 Pro, measured dp'],
  [412, 'large phone'],
  [600, 'small tablet / sw600dp'],
  [744, 'tablet portrait'],
  [800, 'tablet'],
  [1280, 'tablet landscape'],
];

// ── 1. a row must never exceed the width it was given ────────────────
{
  for (const [w, name] of SCREENS) {
    const inner = contentWidth(w);

    const tc = tileColumns(w);
    const tw = columnWidth(inner, tc);
    A(tw > 0 && tw * tc + FIN_GAP * (tc - 1) <= inner,
      `1a. ${name} (${w}dp): ${tc} tiles of ${tw}dp fit inside ${inner}dp`);

    const qc = quickActionColumns(w);
    const qw = columnWidth(inner, qc);
    A(qw > 0 && qw * qc + FIN_GAP * (qc - 1) <= inner,
      `1b. ${name} (${w}dp): ${qc} actions of ${qw}dp fit inside ${inner}dp`);

    // ...and never refuse space that exists: one more column must NOT fit.
    if (qc < QA_MAX_COLS) {
      const next = qc + 1;
      A(columnWidth(inner, next) < QA_MIN_DP,
        `1c. ${name} (${w}dp): ${next} actions would be under ${QA_MIN_DP}dp, so ${qc} is right`);
    }
  }
}

// ── 2. quick-action tiles stay legible at every width ────────────────
{
  for (const [w, name] of SCREENS) {
    const qw = columnWidth(contentWidth(w), quickActionColumns(w));
    A(qw >= QA_MIN_DP - 1,   // -1 absorbs the floor()
      `2. ${name} (${w}dp): action tile ${qw}dp is at least the ${QA_MIN_DP}dp floor`);
  }
}

// ── 3. columns are clamped at both ends ──────────────────────────────
{
  for (const w of [200, 320, 390, 744, 1280, 4000]) {
    const qc = quickActionColumns(w);
    A(qc >= QA_MIN_COLS && qc <= QA_MAX_COLS, `3a. ${w}dp: ${qc} columns is inside [${QA_MIN_COLS}, ${QA_MAX_COLS}]`);
  }
  A(quickActionColumns(4000) === quickActionColumns(FIN_CONTENT_MAX_DP),
    '3b. past the content cap, extra window width adds no more columns');
}

// ── 4. degenerate inputs do not produce a broken layout ──────────────
{
  // Dimensions can report 0 mid-rotation; a NaN here would silently blank a screen.
  for (const bad of [0, -1, NaN, Infinity]) {
    A(contentWidth(bad) === 0, `4a. contentWidth(${bad}) is 0, not NaN`);
    A(quickActionColumns(bad) === QA_MIN_COLS, `4b. quickActionColumns(${bad}) falls back to ${QA_MIN_COLS}`);
    A(columnWidth(bad, 4) === 0, `4c. columnWidth(${bad}, 4) is 0, not negative`);
  }
  A(columnWidth(300, 0) === 0, '4d. zero columns is 0, not a divide-by-zero');
}

// ── 5. the money-wrapping rule that the 320dp artboard found ─────────
{
  A(heroStacks(320), '5a. 320dp stacks the hero, so ₹4,52,000 cannot break mid-number');
  A(!heroStacks(390), '5b. 390dp splits it side by side');
  A(heroStacks(HERO_STACK_BELOW_DP - 1) && !heroStacks(HERO_STACK_BELOW_DP),
    '5c. the stack threshold is exactly HERO_STACK_BELOW_DP');
}

// ── 6. agreement with the Figma artboards ────────────────────────────
// Changing a breakpoint without reopening the design file fails here.
{
  const BOARDS: [number, number, number, string][] = [
    // width, tileCols, quickActionCols, artboard name
    [320, 2, 3, 'Dashboard · 320dp · small phone'],
    [390, 2, 4, 'Dashboard · 390dp'],
    [744, 4, 6, 'Dashboard · 744dp · tablet'],
  ];
  for (const [w, tc, qc, board] of BOARDS) {
    A(tileColumns(w) === tc, `6a. ${board}: ${tc} tile columns`);
    A(quickActionColumns(w) === qc, `6b. ${board}: ${qc} quick-action columns`);
  }
  A(contentWidth(744) === FIN_CONTENT_MAX_DP - FIN_GUTTER * 2,
    '6c. the tablet board reads at the capped column width, not the full 744dp');
}

// ── 7. no finance screen has gone back to hardcoded device numbers ───
{
  const ROOT = join(__dirname, '..', '..');
  const FILES = [
    'app/finance/index.tsx',
    'components/finance/ui.tsx',
    'constants/financeTheme.ts',
  ];
  for (const f of FILES) {
    const src = readFileSync(join(ROOT, f), 'utf8');
    const code = src.split('\n').filter(l => !/^\s*(\/\/|\*|\/\*)/.test(l)).join('\n');

    // the specific device widths the brief calls out
    A(!/\b(?:360|375|390|393|411|412|414|428|1080|1920|2340)\b/.test(code),
      `7a. ${f} contains no hardcoded device dimension`);

    // the Platform.OS status-bar guess the header used to carry
    A(!/paddingTop:\s*Platform\.OS/.test(code),
      `7b. ${f} does not guess the status bar height from Platform.OS`);
  }

  // the dashboard must derive its grids, not count them out by hand.
  // Comments are stripped first — this file documents the value it removed.
  const dashSrc = readFileSync(join(ROOT, 'app/finance/index.tsx'), 'utf8');
  const dash = dashSrc.split('\n').filter(l => !/^\s*(\/\/|\*|\/\*)/.test(l)).join('\n');
  A(/quickActionColumns|ActionGrid/.test(dash), '7c. the dashboard derives its quick-action columns');
  A(!/width:\s*'22%'/.test(dash), '7d. ...and the fixed 22% action tile is gone');
}

// ── 8. every finance colour pair clears WCAG AA ──────────────────────
// The palette is read out of the source rather than imported, because
// constants/financeTheme.ts imports constants/theme.ts which imports
// react-native — not loadable under plain node. Parsing the literals keeps this
// check runnable in the same `tsx` pass as everything else.
{
  const ROOT = join(__dirname, '..', '..');
  const whole = readFileSync(join(ROOT, 'constants/financeTheme.ts'), 'utf8');
  // Scope to the FIN block. The file now also holds FIN_DARK, which repeats
  // every key with a different value — an unscoped scan takes the LAST match
  // and silently grades the light palette using dark-mode colours. That is how
  // this check started reporting white-on-brandDeep at 3.74:1: it had picked up
  // dark's #9D6FD0 instead of light's #6D3FA8.
  const finStart = whole.indexOf('export const FIN = {');
  const src = whole.slice(finStart, whole.indexOf('} as const;', finStart));

  const P: Record<string, string> = {};
  for (const m of src.matchAll(/^\s{2}(\w+):\s*'(#[0-9A-Fa-f]{6})'/gm)) P[m[1]] = m[2];

  const lum = (h: string) => {
    const n = parseInt(h.slice(1), 16);
    const ch = [(n >> 16) & 255, (n >> 8) & 255, n & 255].map(v => {
      const c = v / 255;
      return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
    });
    return 0.2126 * ch[0] + 0.7152 * ch[1] + 0.0722 * ch[2];
  };
  const ratio = (a: string, b: string) => {
    const [x, y] = [lum(a), lum(b)].sort((p, q) => q - p);
    return (x + 0.05) / (y + 0.05);
  };

  // fg, bg, the AA bar, and what it is
  const PAIRS: [string, string, number, string][] = [
    ['text', 'cardSolid', 4.5, 'body text on a card'],
    ['text', 'bgTop', 4.5, 'body text on the ice ground (top)'],
    ['text', 'bgBottom', 4.5, 'body text on the ice ground (bottom)'],
    ['sub', 'cardSolid', 4.5, 'secondary text on a card'],
    ['sub', 'bgBottom', 4.5, 'secondary text on the ground'],
    ['faint', 'cardSolid', 4.5, 'placeholder / hint text'],
    ['good', 'cardSolid', 4.5, 'a gain figure on a card'],
    ['good', 'goodSoft', 4.5, 'a gain pill'],
    ['bad', 'cardSolid', 4.5, 'a loss figure on a card'],
    ['bad', 'badSoft', 4.5, 'an overdue pill'],
    ['warn', 'cardSolid', 4.5, 'a pending figure on a card'],
    ['warn', 'warnSoft', 4.5, 'a pending pill'],
    ['info', 'cardSolid', 4.5, 'an informational figure'],
    ['info', 'infoSoft', 4.5, 'an informational pill'],
    ['brandInk', 'brandSoft', 4.5, 'a label on a soft brand fill'],
    ['brandInk', 'cardSolid', 4.5, 'the selected segment label'],
    ['onBrand', 'brandDeep', 4.5, 'the primary button label'],
    ['onBrand', 'brandInk', 4.5, 'hero text at the darkest gradient stop'],
    ['sub', 'card2', 4.5, 'a completed pill'],
  ];

  for (const [fg, bg, bar, what] of PAIRS) {
    A(!!P[fg] && !!P[bg], `8a. both ${fg} and ${bg} were parsed out of the palette`);
    if (!P[fg] || !P[bg]) continue;
    const r = ratio(P[fg], P[bg]);
    A(r >= bar, `8b. ${what}: ${fg} on ${bg} is ${r.toFixed(2)}:1 (needs ${bar})`);
  }

  // The hero gradient runs brandInk → brandDeep → brand. White has to survive
  // the LIGHTEST stop, which is the one that would fail.
  A(ratio('#FFFFFF', P.brandDeep) >= 4.5,
    `8c. white on the hero's mid gradient stop is ${ratio('#FFFFFF', P.brandDeep).toFixed(2)}:1`);
}

// ── 9. StatTile keeps the flex that three screens depend on ──────────
// Dropping `flex: 1` from the tile style is invisible on the dashboard (where
// TileGrid gives each tile a fixed-width wrapper) and silently collapses the
// bare `tileRow` on reports / customer / chitti. It was removed once already.
{
  const ROOT = join(__dirname, '..', '..');
  const ui = readFileSync(join(ROOT, 'components/finance/ui.tsx'), 'utf8');
  const tileLine = ui.split('\n').find(l => /^\s{2}tile:\s*\{/.test(l)) ?? '';
  A(/flex:\s*1/.test(tileLine), '9a. the StatTile style still declares flex: 1');

  for (const f of ['app/finance/reports.tsx', 'app/finance/customer.tsx', 'app/finance/chitti/[id].tsx']) {
    const src = readFileSync(join(ROOT, f), 'utf8');
    A(/tileRow:\s*\{[^}]*flexDirection:\s*'row'/.test(src),
      `9b. ${f} still lays its tiles out in a row`);
  }
}

// ── 10. Shop Book is the second consumer of this contract ────────────
// The grid lives under finance/ because that is where it was built, but Shop
// Book's owner dashboard now derives its layout from the same functions. Its
// two grids used to be a `minWidth: '46%'` tile wrap and a hand-split 6 + 2
// link row — both of which stayed put on a tablet. Guard the swap.
{
  const ROOT = join(__dirname, '..', '..');
  const src = readFileSync(join(ROOT, 'app/shop-book.tsx'), 'utf8');
  // Strip JSX `{/* … */}` blocks as well as `//` lines. Without the first of
  // these the scan reads the comment that DOCUMENTS the removed value and
  // reports the value as still present — which it did, on the first run.
  const code = src
    .replace(/\{\/\*[\s\S]*?\*\/\}/g, '')
    .split('\n').filter(l => !/^\s*(\/\/|\*|\/\*)/.test(l)).join('\n');

  A(/<TileGrid>/.test(code), '10a. the dashboard totals use TileGrid');
  A(/<ActionGrid>/.test(code), '10b. the dashboard quick links use ActionGrid');
  A(!/minWidth:\s*'4\d%'/.test(code), '10c. no percentage tile width has come back');
  A(!/flexBasis:\s*'30%'/.test(code), '10d. no percentage link-card width has come back');
  A(!/paddingTop:\s*48/.test(code), '10e. the header no longer guesses the status bar height');
  // C.bg transparent + C.card translucent is the whole restyle mechanism: undo
  // either and 53 components quietly go back to being opaque on grey.
  // These moved from `FIN.x` to the palette factory when Shop Book became
  // theme-aware. The invariant is unchanged — transparent ground, translucent
  // pane — so the check follows the spelling rather than being deleted.
  A(/bg:\s*P\.bg\b/.test(code), '10f. the Shop Book ground is still the shared token');
  A(/card:\s*P\.card\b/.test(code), '10g. Shop Book cards are still glass');

  // The reading column. `body` is the content container for every Shop Book
  // screen, so this single rule is what stops a khata list putting a customer
  // name and their balance at opposite edges of a 1200dp window.
  A(/maxWidth:\s*C\.contentMax/.test(code), '10h. the content column is still capped');
  A(/alignSelf:\s*'center'/.test(code), '10i. the capped column still centres');

  // One transaction row. Two callers hand-rolled it before and their money
  // columns drifted apart; if either stops using it, that starts again.
  A(/function TxnRow\(/.test(code), '10j. the shared transaction row exists');
  A((code.match(/<TxnRow\b/g) ?? []).length >= 4, '10k. all four list callers use it');
  // An alpha-washed foreground was invisible once the card underneath became
  // translucent; status pills need a real fill.
  A(!/backgroundColor:\s*color\s*\+\s*'20'/.test(code),
    '10m. status pills use a solid soft fill, not an alpha wash');

  // Currency. Shop Book is multi-country (Shop.currency is a display symbol
  // from the country config), so a hardcoded ₹ mislabels real money. The sweep
  // took 25 call sites down to one legitimate use: the cross-shop loyalty
  // total, which has no single shop and therefore no single currency — the
  // hint beside it says "every ₹100 spent" in so many words.
  const inrCalls = (code.match(/formatINR\(/g) ?? []).length;
  A(inrCalls <= 1, `10n. at most one hardcoded-₹ call remains (found ${inrCalls})`);
  A(/formatINR\(loyalty\?\.totalSpent/.test(code),
    '10o. the one that remains is still the cross-shop loyalty total');

  // AUTO-RESPONSIVE ON EVERY DEVICE, not on a list of devices. The layout may
  // only ever key off the MEASURED window, so a phone nobody owns yet is
  // handled by the same code as the two on the desk.
  A(!/\b(Redmi|Honor|Pixel|iPhone|Galaxy|isTablet|isPhone)\b\s*[=:?]/.test(code),
    '10p. no per-model branching');
  // Dimensions.get() is a SNAPSHOT — it does not re-run on rotation or on a
  // fold opening, so a layout built from it silently keeps the old width.
  // useWindowDimensions() is the subscribing hook and is what the grids use.
  A(!/Dimensions\.get\(/.test(code),
    '10q. no Dimensions.get snapshot (rotation would not re-layout)');

  // ── theme wiring ──────────────────────────────────────────────────
  // The whole mechanism: `C` and `s` are LET bindings re-pointed by
  // applyScheme, and every component dereferences them at render. Turn either
  // back into a const and dark mode silently stops working while still
  // compiling.
  A(/const makeC = \(P: Palette\)/.test(code), '10r. the palette is a factory over a scheme');
  A(/const makeStyles = /.test(code), '10s. the stylesheet is a factory over the palette');
  A(/^let C = /m.test(code), '10t. C is re-pointable (let, not const)');
  A(/^let s = /m.test(code), '10u. s is re-pointable (let, not const)');
  A(/function applyScheme\(/.test(code), '10v. applyScheme exists');
  A(/applyScheme\(scheme === 'dark'/.test(code), '10w. the screen installs the active scheme');
  // NOT keyed: a key remounts the subtree and device testing showed that drops
  // the user back to the dashboard on a theme change (these phones auto-switch
  // at 22:00). Nothing here is memoized, so a re-render suffices.
  A(!/<IceGround key=/.test(code), '10x. the tree is NOT keyed on the scheme (remount loses the user’s place)');
  A(!/React\.memo|memo\(/.test(code), '10x2. nothing is memoized, so children re-render with the parent');
  // Both palettes must be built once at module load, not per render.
  A(/const LIGHT_S = makeStyles\(/.test(code) && /const DARK_S = makeStyles\(/.test(code),
    '10y. both stylesheets are built once at module load');
  // No component may read the light palette directly, or it would stay light
  // in dark mode. Only the type alias and a comment may mention FIN.
  const finReads = (code.match(/\bFIN\.[a-z]/gi) ?? []);
  A(finReads.length === 0, `10z. no component reads FIN.* directly (found ${finReads.length})`);
  // A large header FILL cannot reuse the accent: in dark that is a glaring slab.
  A(/backgroundColor: C\.headerBg/.test(code), '10aa. the header uses its own fill role');
  A(/color: C\.headerFg/.test(code), '10ab. the header uses its own text role');
  // Colour must never be the only thing distinguishing owed from settled.
  A(/amountNote/.test(code), '10l. the money column still states what the figure means');
}

console.log(failed === 0 ? '\nAll good.\n' : `\n${failed} FAILED\n`);
process.exit(failed === 0 ? 0 : 1);
