// lib/ccwire/codecParity.selftest.ts — run: npx tsx lib/ccwire/codecParity.selftest.ts
//
// ccwire.v1.Frame cross-language parity: TypeScript (lib/ccwire/codec.ts)
// against Rust (services/transport/rust/src/parse.rs), through ONE committed
// fixture both sides assert — __vectors__/codec.json.
//
// HOW THIS FIXTURE DIFFERS FROM frame.json, AND WHY IT IS STRONGER:
// frame.json is generated by Go from literal expectations. codec.json is written
// BY HAND from the protobuf wire specification and generated by nobody, so
// neither implementation can pass it by agreeing with itself. It has already
// earned its keep: the first run failed because the hand-written 2^53+1 varint
// carried one 0x80 too many, and the byte count was then re-derived from the
// spec (groups 0..7, group 7 at shift 49, 0x10 = 2^4, so 2^4 * 2^49 = 2^53)
// rather than copied from whatever the code happened to produce.
//
// SCOPE. Two layers, two sections of the fixture. The 'decode'/'encode' vectors
// are the ROUTING HEADER, where both sides treat the body as opaque bytes, so
// every body there is empty or an untyped field number. The 'bodies' vectors are
// the six TYPED bodies — decoded here by codec.ts and on the Rust side by
// services/transport/rust/src/body.rs, which is what closed the gap where a
// malformed typing_state was refused by TypeScript and accepted by Rust. The
// exclusion list that recorded that gap is now empty, and still asserted: see
// "the scope exclusion" below.
//
// STATUS: NOT WIRED, like codec.ts itself. Nothing on the live path imports
// either; the live transport remains Socket.IO v4 with JSON payloads.

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  decodeFrameMessage, encodeFrameMessage,
  LIMITS, BODY_NAMES, EPHEMERAL_BODIES, TRAFFIC_CLASS_EPHEMERAL, ERROR_CODE,
  type Frame, type Limits,
} from './codec';

const VECTORS = path.join(path.dirname(fileURLToPath(import.meta.url)), '__vectors__', 'codec.json');

let failures = 0;
function check(name: string, ok: boolean, detail?: string): void {
  console.log(`  ${ok ? '✓' : '✗'} ${name}${ok || !detail ? '' : `  (${detail})`}`);
  if (!ok) failures++;
}

// Whitespace is stripped so the fixture may group bytes for a human reader.
const unhex = (s: string): Uint8Array =>
  Uint8Array.from(Buffer.from((s ?? '').replace(/\s+/g, ''), 'hex'));
const tohex = (b: Uint8Array | undefined): string => Buffer.from(b ?? new Uint8Array(0)).toString('hex');

console.log('\nccwire.v1.Frame TS↔Rust parity (hand-written wire vectors)\n');

if (!fs.existsSync(VECTORS)) {
  console.error(`  ✗ ${VECTORS} is missing.`);
  process.exit(1);
}
const v = JSON.parse(fs.readFileSync(VECTORS, 'utf8'));

// ── constants ────────────────────────────────────────────────────────────────
// If these drift, every byte-level vector below is comparing two protocols that
// merely look alike.

console.log('Constants agree with the fixture:');
for (const k of Object.keys(LIMITS) as (keyof typeof LIMITS)[]) {
  check(`LIMITS.${k}`, v.limits[k] === LIMITS[k], `${v.limits[k]} vs ${LIMITS[k]}`);
}
check('TRAFFIC_CLASS_EPHEMERAL',
  v.trafficClassEphemeral === TRAFFIC_CLASS_EPHEMERAL,
  `${v.trafficClassEphemeral} vs ${TRAFFIC_CLASS_EPHEMERAL}`);
check('EPHEMERAL_BODIES allow-list',
  JSON.stringify(v.ephemeralBodies) === JSON.stringify([...EPHEMERAL_BODIES].sort((a, b) => a - b)),
  `${JSON.stringify(v.ephemeralBodies)} vs ${JSON.stringify([...EPHEMERAL_BODIES])}`);
check('oneof body field numbers',
  JSON.stringify(v.bodyFields) === JSON.stringify(Object.keys(BODY_NAMES).map(Number).sort((a, b) => a - b)),
  'BODY_NAMES drifted from envelope.proto');

// ── the scope exclusion ──────────────────────────────────────────────────────
// The one place the two implementations are known to differ. Asserted so it
// cannot silently widen: a vector that leaned on a TS-only body would prove
// nothing about Rust, which does not decode those bodies at all.

console.log('\nNo vector leans on a body only TypeScript decodes:');
{
  const excluded: number[] = v.bodiesTypedByTypescriptOnly;
  let bad = 0;
  for (const c of v.decode) {
    const hasContent = !!(c.bodyHex && c.bodyHex.length);
    if (c.bodyField != null && hasContent && excluded.includes(c.bodyField)) {
      check(c.name, false, `body ${c.bodyField} is TS-only`);
      bad++;
    }
  }
  check(`${v.decode.length} decode vectors stay inside the agreed set`, bad === 0);
}

// ── decode ───────────────────────────────────────────────────────────────────

console.log('\nTS decodes the hand-written vectors as specified:');
for (const c of v.decode) {
  const r = decodeFrameMessage(unhex(c.inputHex), {
    maxBytes: c.maxBytes || undefined,
    limits: c.limits as Limits | undefined,
    depth: c.depth,
  });

  if (c.ok) {
    if (!r.ok) {
      check(c.name, false, `rejected: ${r.error} — ${r.detail}`);
      continue;
    }
    const f = r.frame!;
    // A typed body decodes into `value` and leaves `raw` unset; an untyped one
    // fills `raw`. Every shared vector is empty-or-untyped, so `raw ?? empty` is
    // the body bytes in both cases.
    const bodyHex = tohex(f.raw);
    const unknownHex = (f.unknown ?? []).map(tohex);
    const ok =
      (f.request_id ?? '') === c.requestId &&
      (f.traffic_class ?? 0) === c.trafficClass &&
      (f.stream ?? 0) === c.stream &&
      (f.seq ?? '0') === c.seq &&
      (f.depends_on ?? '0') === c.dependsOn &&
      (f.body_field ?? null) === c.bodyField &&
      bodyHex === (c.bodyHex ?? '') &&
      JSON.stringify(unknownHex) === JSON.stringify(c.unknownHex ?? []);
    check(c.name, ok,
      `rid=${JSON.stringify(f.request_id)} tc=${f.traffic_class} stream=${f.stream} ` +
      `seq=${f.seq} dep=${f.depends_on} body=${f.body_field} raw=${bodyHex} ` +
      `unknown=${JSON.stringify(unknownHex)}`);
  } else {
    const ok = !r.ok && r.error === c.error && r.errorCode === c.errorCode;
    check(c.name, ok,
      r.ok ? 'ACCEPTED input the fixture refuses'
           : `got ${r.error}/${r.errorCode}, want ${c.error}/${c.errorCode}`);
  }
}

// ── typed bodies ─────────────────────────────────────────────────────────────
// The six bodies both sides now decode. codec.ts has no body-only entry point —
// the frame is the only door in — so each body is wrapped in the smallest legal
// frame: traffic_class CONTROL, then the body's own tag. That wrapper charges
// exactly one level of nesting, which is why the Rust test decodes these at
// depth 1 too.

const wVarint = (n: number): number[] => {
  const o: number[] = [];
  while (n >= 128) { o.push((n & 0x7f) | 0x80); n = Math.floor(n / 128); }
  o.push(n);
  return o;
};
const wrap = (field: number, body: Uint8Array): Uint8Array =>
  Uint8Array.from([0x10, 0x01, ...wVarint(field * 8 + 2), ...wVarint(body.length), ...body]);

/** The decoded body in the fixture's shape: bytes as hex, keys sorted. */
const norm = (x: any): any => {
  if (x instanceof Uint8Array) return tohex(x);
  if (Array.isArray(x)) return x.map(norm);
  if (x && typeof x === 'object') {
    const o: any = {};
    for (const k of Object.keys(x).sort()) if (x[k] !== undefined) o[k] = norm(x[k]);
    return o;
  }
  return x;
};

console.log('\nTS decodes the typed bodies as the fixture specifies:');
for (const c of v.bodies ?? []) {
  const r = decodeFrameMessage(wrap(c.field, unhex(c.bodyHex)), { limits: c.limits as Limits });

  if (c.ok) {
    if (!r.ok) { check(c.name, false, `rejected: ${r.error} — ${r.detail}`); continue; }
    const got = JSON.stringify(norm(r.frame!.value));
    const want = JSON.stringify(norm(c.value));
    check(c.name, r.frame!.body_field === c.field && got === want, `${got}\n      want ${want}`);
  } else {
    check(c.name, !r.ok && r.error === c.error && r.errorCode === c.errorCode,
      r.ok ? 'ACCEPTED a body the fixture refuses' : `got ${r.error}/${r.errorCode}`);
  }
}
check(`${(v.bodies ?? []).length} body vectors, covering all six typed bodies`,
  new Set((v.bodies ?? []).map((c: any) => c.field)).size === 6);

// ── encode ───────────────────────────────────────────────────────────────────

console.log('\nTS encodes the bytes the fixture specifies:');
for (const c of v.encode) {
  const s = c.frame;
  const f: Frame = {
    request_id: s.requestId ?? '',
    traffic_class: s.trafficClass ?? 0,
    stream: s.stream ?? 0,
    seq: s.seq ?? '0',
    depends_on: s.dependsOn ?? '0',
    body_field: s.bodyField ?? undefined,
    raw: s.bodyField != null ? unhex(s.bodyHex ?? '') : undefined,
    unknown: (s.unknownHex ?? []).map(unhex),
  };
  const r = encodeFrameMessage(f);
  const wantOk = c.ok !== false;

  if (wantOk) {
    const got = tohex(r.bytes);
    const want = tohex(unhex(c.outHex));
    check(c.name, r.ok && got === want,
      r.ok ? `got ${got} want ${want}` : `refused: ${r.error} — ${r.detail}`);
  } else {
    check(c.name, !r.ok && r.error === c.error && r.errorCode === c.errorCode,
      r.ok ? 'ENCODED a frame the fixture refuses' : `got ${r.error}/${r.errorCode}`);
  }
}

// ── round trip ───────────────────────────────────────────────────────────────
// Preservation of unknown fields is only real if it survives the re-encode.

console.log('\nEvery accepted vector re-encodes to the bytes it came from:');
for (const c of v.decode) {
  if (!c.ok) continue;
  // Last-wins genuinely discards the earlier duplicate, so this one case
  // canonicalises rather than round-trips. Naming it records that; skipping it
  // silently would hide it.
  if (c.name.includes('last-wins')) continue;

  const input = unhex(c.inputHex);
  const r = decodeFrameMessage(input, { limits: c.limits as Limits | undefined });
  if (!r.ok) { check(c.name, false, `decode: ${r.error}`); continue; }
  const back = encodeFrameMessage(r.frame!);
  check(c.name, back.ok && tohex(back.bytes) === tohex(input),
    back.ok ? `${tohex(back.bytes)} vs ${tohex(input)}` : `re-encode: ${back.error}`);
}

// ── the ErrorCode mapping ────────────────────────────────────────────────────
// A caller puts this number in an Error frame. If the two sides map the same
// refusal to different codes, the peer is told the wrong thing about why.

console.log('\nErrorCode mapping matches the fixture:');
for (const c of [...v.decode, ...v.encode, ...(v.bodies ?? [])]) {
  if (c.ok !== false) continue;
  check(`${c.error} → ${c.errorCode}`,
    ERROR_CODE[c.error as keyof typeof ERROR_CODE] === c.errorCode,
    `codec.ts says ${ERROR_CODE[c.error as keyof typeof ERROR_CODE]}`);
}

console.log(failures
  ? `\n  ${failures} FAILED — TypeScript and Rust have diverged on ccwire.v1.Frame\n`
  : '\n  all ccwire.v1.Frame TS↔Rust parity checks passed\n');
process.exit(failures ? 1 : 0);
