// lib/ccwire/codecParity.selftest.ts — run: npx tsx lib/ccwire/codecParity.selftest.ts
//
// ccwire.v1.Frame cross-language parity: TypeScript (lib/ccwire/codec.ts)
// against Rust (services/transport/rust/src/parse.rs), through ONE committed
// fixture both sides assert — __vectors__/codec.json.
//
// HOW THIS FIXTURE DIFFERS FROM frame.json, AND WHY IT IS STRONGER:
// frame.json is generated by Go from literal expectations. codec.json is written
// BY HAND from the protobuf wire specification and generated by nobody, so
// neither implementation can pass it by agreeing with itself. It has already
// earned its keep: the first run failed because the hand-written 2^53+1 varint
// carried one 0x80 too many, and the byte count was then re-derived from the
// spec (groups 0..7, group 7 at shift 49, 0x10 = 2^4, so 2^4 * 2^49 = 2^53)
// rather than copied from whatever the code happened to produce.
//
// SCOPE. Two layers, two sections of the fixture. The 'decode'/'encode' vectors
// are the ROUTING HEADER, where both sides treat the body as opaque bytes, so
// every body there is empty or an untyped field number. The 'bodies' vectors are
// the six TYPED bodies — decoded here by codec.ts and on the Rust side by
// services/transport/rust/src/body.rs, which is what closed the gap where a
// malformed typing_state was refused by TypeScript and accepted by Rust. The
// exclusion list that records what is STILL one-sided — app_event, field 100,
// typed here and opaque in Go and Rust — is asserted below so no vector can
// quietly come to depend on a body the other two never decode: see "the scope
// exclusion".
//
// STATUS: NOT WIRED, like codec.ts itself. Nothing on the live path imports
// either; the live transport remains Socket.IO v4 with JSON payloads.

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  decodeFrameMessage, encodeFrameMessage,
  LIMITS, BODY_NAMES, EPHEMERAL_BODIES, TRAFFIC_CLASS_EPHEMERAL, ERROR_CODE, APP_EVENT_LOGICAL_MAX, APP_EVENT_JSON_MAX,
  type Frame, type Limits,
} from './codec';

const VECTORS = path.join(path.dirname(fileURLToPath(import.meta.url)), '__vectors__', 'codec.json');

let failures = 0;
function check(name: string, ok: boolean, detail?: string): void {
  console.log(`  ${ok ? '✓' : '✗'} ${name}${ok || !detail ? '' : `  (${detail})`}`);
  if (!ok) failures++;
}

// Whitespace is stripped so the fixture may group bytes for a human reader.
const unhex = (s: string): Uint8Array =>
  Uint8Array.from(Buffer.from((s ?? '').replace(/\s+/g, ''), 'hex'));
const tohex = (b: Uint8Array | undefined): string => Buffer.from(b ?? new Uint8Array(0)).toString('hex');

console.log('\nccwire.v1.Frame TS↔Rust parity (hand-written wire vectors)\n');

if (!fs.existsSync(VECTORS)) {
  console.error(`  ✗ ${VECTORS} is missing.`);
  process.exit(1);
}
const v = JSON.parse(fs.readFileSync(VECTORS, 'utf8'));

// ── constants ────────────────────────────────────────────────────────────────
// If these drift, every byte-level vector below is comparing two protocols that
// merely look alike.

console.log('Constants agree with the fixture:');
for (const k of Object.keys(LIMITS) as (keyof typeof LIMITS)[]) {
  check(`LIMITS.${k}`, v.limits[k] === LIMITS[k], `${v.limits[k]} vs ${LIMITS[k]}`);
}
check('TRAFFIC_CLASS_EPHEMERAL',
  v.trafficClassEphemeral === TRAFFIC_CLASS_EPHEMERAL,
  `${v.trafficClassEphemeral} vs ${TRAFFIC_CLASS_EPHEMERAL}`);
check('EPHEMERAL_BODIES allow-list',
  JSON.stringify(v.ephemeralBodies) === JSON.stringify([...EPHEMERAL_BODIES].sort((a, b) => a - b)),
  `${JSON.stringify(v.ephemeralBodies)} vs ${JSON.stringify([...EPHEMERAL_BODIES])}`);
check('oneof body field numbers',
  JSON.stringify(v.bodyFields) === JSON.stringify(Object.keys(BODY_NAMES).map(Number).sort((a, b) => a - b)),
  'BODY_NAMES drifted from envelope.proto');

// ── the scope exclusion ──────────────────────────────────────────────────────
// The one place the two implementations are known to differ. Asserted so it
// cannot silently widen: a vector that leaned on a TS-only body would prove
// nothing about Rust, which does not decode those bodies at all.

console.log('\nNo vector leans on a body only TypeScript decodes:');
{
  const excluded: number[] = v.bodiesTypedByTypescriptOnly;
  let bad = 0;
  for (const c of v.decode) {
    const hasContent = !!(c.bodyHex && c.bodyHex.length);
    if (c.bodyField != null && hasContent && excluded.includes(c.bodyField)) {
      check(c.name, false, `body ${c.bodyField} is TS-only`);
      bad++;
    }
  }
  check(`${v.decode.length} decode vectors stay inside the agreed set`, bad === 0);
}

// ── decode ───────────────────────────────────────────────────────────────────

console.log('\nTS decodes the hand-written vectors as specified:');
for (const c of v.decode) {
  const r = decodeFrameMessage(unhex(c.inputHex), {
    maxBytes: c.maxBytes || undefined,
    limits: c.limits as Limits | undefined,
    depth: c.depth,
  });

  if (c.ok) {
    if (!r.ok) {
      check(c.name, false, `rejected: ${r.error} — ${r.detail}`);
      continue;
    }
    const f = r.frame!;
    // A typed body decodes into `value` and leaves `raw` unset; an untyped one
    // fills `raw`. Every shared vector is empty-or-untyped, so `raw ?? empty` is
    // the body bytes in both cases.
    const bodyHex = tohex(f.raw);
    const unknownHex = (f.unknown ?? []).map(tohex);
    const ok =
      (f.request_id ?? '') === c.requestId &&
      (f.traffic_class ?? 0) === c.trafficClass &&
      (f.stream ?? 0) === c.stream &&
      (f.seq ?? '0') === c.seq &&
      (f.depends_on ?? '0') === c.dependsOn &&
      (f.body_field ?? null) === c.bodyField &&
      bodyHex === (c.bodyHex ?? '') &&
      JSON.stringify(unknownHex) === JSON.stringify(c.unknownHex ?? []);
    check(c.name, ok,
      `rid=${JSON.stringify(f.request_id)} tc=${f.traffic_class} stream=${f.stream} ` +
      `seq=${f.seq} dep=${f.depends_on} body=${f.body_field} raw=${bodyHex} ` +
      `unknown=${JSON.stringify(unknownHex)}`);
  } else {
    const ok = !r.ok && r.error === c.error && r.errorCode === c.errorCode;
    check(c.name, ok,
      r.ok ? 'ACCEPTED input the fixture refuses'
           : `got ${r.error}/${r.errorCode}, want ${c.error}/${c.errorCode}`);
  }
}

// ── typed bodies ─────────────────────────────────────────────────────────────
// The six bodies both sides now decode. codec.ts has no body-only entry point —
// the frame is the only door in — so each body is wrapped in the smallest legal
// frame: traffic_class CONTROL, then the body's own tag. That wrapper charges
// exactly one level of nesting, which is why the Rust test decodes these at
// depth 1 too.

const wVarint = (n: number): number[] => {
  const o: number[] = [];
  while (n >= 128) { o.push((n & 0x7f) | 0x80); n = Math.floor(n / 128); }
  o.push(n);
  return o;
};
const wrap = (field: number, body: Uint8Array): Uint8Array =>
  Uint8Array.from([0x10, 0x01, ...wVarint(field * 8 + 2), ...wVarint(body.length), ...body]);

/** The decoded body in the fixture's shape: bytes as hex, keys sorted. */
const norm = (x: any): any => {
  if (x instanceof Uint8Array) return tohex(x);
  if (Array.isArray(x)) return x.map(norm);
  if (x && typeof x === 'object') {
    const o: any = {};
    for (const k of Object.keys(x).sort()) if (x[k] !== undefined) o[k] = norm(x[k]);
    return o;
  }
  return x;
};

console.log('\nTS decodes the typed bodies as the fixture specifies:');
for (const c of v.bodies ?? []) {
  const r = decodeFrameMessage(wrap(c.field, unhex(c.bodyHex)), { limits: c.limits as Limits });

  if (c.ok) {
    if (!r.ok) { check(c.name, false, `rejected: ${r.error} — ${r.detail}`); continue; }
    const got = JSON.stringify(norm(r.frame!.value));
    const want = JSON.stringify(norm(c.value));
    check(c.name, r.frame!.body_field === c.field && got === want, `${got}\n      want ${want}`);
  } else {
    check(c.name, !r.ok && r.error === c.error && r.errorCode === c.errorCode,
      r.ok ? 'ACCEPTED a body the fixture refuses' : `got ${r.error}/${r.errorCode}`);
  }
}
check(`${(v.bodies ?? []).length} body vectors, covering all six typed bodies`,
  new Set((v.bodies ?? []).map((c: any) => c.field)).size === 6);

// ── encode ───────────────────────────────────────────────────────────────────

console.log('\nTS encodes the bytes the fixture specifies:');
for (const c of v.encode) {
  const s = c.frame;
  const f: Frame = {
    request_id: s.requestId ?? '',
    traffic_class: s.trafficClass ?? 0,
    stream: s.stream ?? 0,
    seq: s.seq ?? '0',
    depends_on: s.dependsOn ?? '0',
    body_field: s.bodyField ?? undefined,
    raw: s.bodyField != null ? unhex(s.bodyHex ?? '') : undefined,
    unknown: (s.unknownHex ?? []).map(unhex),
  };
  const r = encodeFrameMessage(f);
  const wantOk = c.ok !== false;

  if (wantOk) {
    const got = tohex(r.bytes);
    const want = tohex(unhex(c.outHex));
    check(c.name, r.ok && got === want,
      r.ok ? `got ${got} want ${want}` : `refused: ${r.error} — ${r.detail}`);
  } else {
    check(c.name, !r.ok && r.error === c.error && r.errorCode === c.errorCode,
      r.ok ? 'ENCODED a frame the fixture refuses' : `got ${r.error}/${r.errorCode}`);
  }
}

// ── encode-side bounds ───────────────────────────────────────────────────────
// Every bound is enforced on ENCODE as well as DECODE, so a local bug fails on
// the machine that has the stack trace rather than on the peer that only has
// bytes. These three are too large to live in the shared fixture — a 4 KiB
// request_id and a 1 MiB body would be megabytes of hex — so they are built
// here, and the Go (internal/ccwire/codec.go) and Rust
// (transport/rust/src/parse.rs) encoders are read as the specification for what
// each must return.
//
// The TYPED error matters as much as the refusal: a caller switches on it to
// pick the errors.proto ErrorCode, and the encode and decode paths must hand it
// the same value for the same overrun.

console.log('\nEncode refuses what decode refuses, with the same typed error:');
{
  const ok = (r: ReturnType<typeof encodeFrameMessage>, err: keyof typeof ERROR_CODE) =>
    !r.ok && r.error === err && r.errorCode === ERROR_CODE[err];
  const why = (r: ReturnType<typeof encodeFrameMessage>) =>
    r.ok ? 'ENCODED it' : `got ${r.error}/${r.errorCode}`;

  // request_id is bounded in BYTES, before UTF-8 is considered — the same gate
  // readString applies. Go refuses with ErrStringTooLong, Rust StringTooLong.
  const atCap = encodeFrameMessage({
    traffic_class: 1, request_id: 'a'.repeat(LIMITS.max_string_field_bytes),
  });
  check('request_id exactly at max_string_field_bytes still encodes', atCap.ok,
    atCap.ok ? '' : `refused: ${atCap.error}`);

  const overCap = encodeFrameMessage({
    traffic_class: 1, request_id: 'a'.repeat(LIMITS.max_string_field_bytes + 1),
  });
  check('request_id over max_string_field_bytes → STRING_TOO_LONG',
    ok(overCap, 'STRING_TOO_LONG'), why(overCap));

  // A 2049-CHARACTER id whose UTF-8 is 4098 bytes. Bounding the JS string length
  // instead would let a 3x multi-byte payload straight through the gate.
  const multibyte = encodeFrameMessage({
    traffic_class: 1, request_id: 'é'.repeat(LIMITS.max_string_field_bytes / 2 + 1),
  });
  check('a multi-byte request_id is measured in bytes, not characters',
    ok(multibyte, 'STRING_TOO_LONG'), why(multibyte));

  // A negotiated Limits may only tighten, and encode must honour the tightening
  // too — otherwise the peer that asked for a smaller bound is the one that
  // finds out it was ignored.
  const negotiated = encodeFrameMessage(
    { traffic_class: 1, request_id: 'a'.repeat(64) },
    { limits: { max_string_field_bytes: 32 } });
  check('a negotiated-down max_string_field_bytes binds encode',
    ok(negotiated, 'STRING_TOO_LONG'), why(negotiated));

  // The oneof is CLOSED. Field 7 is not an extension point: the peer preserves
  // it as an unknown field, sees no body, and refuses the whole frame — a
  // refusal with no stack trace anywhere near the bug.
  for (const n of [7, 0, 15, 101, 113]) {
    const r = encodeFrameMessage({ traffic_class: 1, body_field: n, raw: new Uint8Array(0) });
    check(`body_field ${n} is not a oneof arm → PROTOCOL_VIOLATION`,
      ok(r, 'PROTOCOL_VIOLATION'), why(r));
  }
  // The other half of a closed-set check: the new refusal must not have eaten a
  // legal arm. traffic_class CONTROL, so the EPHEMERAL invariant is not in play.
  const arms = Object.keys(BODY_NAMES).map(Number);
  const rejected = arms.filter((n) =>
    !encodeFrameMessage({ traffic_class: 1, body_field: n, raw: new Uint8Array(0) }).ok);
  check(`all ${arms.length} real oneof arms still encode`, rejected.length === 0,
    `refused ${JSON.stringify(rejected)}`);

  // max_message_body_bytes, NOT the frame ceiling: the body limit is LARGER
  // than a frame because a body arrives reassembled from fragments, so the
  // whole-frame check at the end of encode is not a substitute for this one.
  // It is reached with a raised maxBytes, which is what proves they are
  // separate gates — SIZE_OVER_MAX here would mean the body bound never ran.
  const bigBody = encodeFrameMessage(
    { traffic_class: 1, body_field: 48, raw: new Uint8Array(LIMITS.max_message_body_bytes + 1) },
    { maxBytes: LIMITS.max_message_body_bytes * 2 });
  check('body over max_message_body_bytes → BYTES_TOO_LONG',
    ok(bigBody, 'BYTES_TOO_LONG'), why(bigBody));

  const bodyAtCap = encodeFrameMessage(
    { traffic_class: 1, body_field: 48, raw: new Uint8Array(LIMITS.max_message_body_bytes) },
    { maxBytes: LIMITS.max_message_body_bytes * 2 });
  check('body exactly at max_message_body_bytes still encodes', bodyAtCap.ok,
    bodyAtCap.ok ? '' : `refused: ${bodyAtCap.error}`);

  // THE ONE DOCUMENTED EXCEPTION, and the reason it is not a hole. appEventsV1
  // is a TypeScript-side negotiation Go and Rust do not have — the same
  // asymmetry as app_event itself (see `bodiesTypedByTypescriptOnly`). Decode
  // already raises the ceiling to APP_EVENT_LOGICAL_MAX under that flag, so
  // encode must too, or this build would refuse to produce a body it will
  // happily accept off the wire. Above that ceiling it still refuses, and with
  // the flag OFF — the only mode the other two implementations run in — the
  // bound is max_message_body_bytes exactly.
  // APP_EVENT_JSON_MAX (1.5 MiB), not APP_EVENT_LOGICAL_MAX: the logical max is
  // the SAME number as frame.ts's hard MAX_FRAME_BYTES, so a body sitting
  // exactly on it can never fit a frame and SIZE_OVER_MAX is the honest answer
  // there. 1.5 MiB is the size the live app-event path actually produces — over
  // max_message_body_bytes, under the hard ceiling — so it is the one that
  // distinguishes the two rules.
  const appEvent = (n: number, flag = true) => encodeFrameMessage(
    { traffic_class: 1, body_field: 100, raw: new Uint8Array(n) },
    { maxBytes: APP_EVENT_LOGICAL_MAX, appEventsV1: flag });
  check('appEventsV1 raises the body ceiling past max_message_body_bytes',
    appEvent(APP_EVENT_JSON_MAX).ok, why(appEvent(APP_EVENT_JSON_MAX)));
  check('the same body without appEventsV1 → BYTES_TOO_LONG',
    ok(appEvent(APP_EVENT_JSON_MAX, false), 'BYTES_TOO_LONG'),
    why(appEvent(APP_EVENT_JSON_MAX, false)));
  check('appEventsV1 still refuses above APP_EVENT_LOGICAL_MAX',
    ok(appEvent(APP_EVENT_LOGICAL_MAX + 1), 'BYTES_TOO_LONG'),
    why(appEvent(APP_EVENT_LOGICAL_MAX + 1)));

}

// ── round trip ───────────────────────────────────────────────────────────────
// Preservation of unknown fields is only real if it survives the re-encode.

console.log('\nEvery accepted vector re-encodes to the bytes it came from:');
for (const c of v.decode) {
  if (!c.ok) continue;
  // Last-wins genuinely discards the earlier duplicate, so this one case
  // canonicalises rather than round-trips. Naming it records that; skipping it
  // silently would hide it.
  if (c.name.includes('last-wins')) continue;

  const input = unhex(c.inputHex);
  const r = decodeFrameMessage(input, { limits: c.limits as Limits | undefined });
  if (!r.ok) { check(c.name, false, `decode: ${r.error}`); continue; }
  const back = encodeFrameMessage(r.frame!);
  check(c.name, back.ok && tohex(back.bytes) === tohex(input),
    back.ok ? `${tohex(back.bytes)} vs ${tohex(input)}` : `re-encode: ${back.error}`);
}

// ── the ErrorCode mapping ────────────────────────────────────────────────────
// A caller puts this number in an Error frame. If the two sides map the same
// refusal to different codes, the peer is told the wrong thing about why.

console.log('\nErrorCode mapping matches the fixture:');
for (const c of [...v.decode, ...v.encode, ...(v.bodies ?? [])]) {
  if (c.ok !== false) continue;
  check(`${c.error} → ${c.errorCode}`,
    ERROR_CODE[c.error as keyof typeof ERROR_CODE] === c.errorCode,
    `codec.ts says ${ERROR_CODE[c.error as keyof typeof ERROR_CODE]}`);
}

console.log(failures
  ? `\n  ${failures} FAILED — TypeScript and Rust have diverged on ccwire.v1.Frame\n`
  : '\n  all ccwire.v1.Frame TS↔Rust parity checks passed\n');
process.exit(failures ? 1 : 0);
