// lib/ccwire/parity.selftest.ts — run: npx tsx lib/ccwire/parity.selftest.ts
//
// CC-Wire v1 cross-language parity: TypeScript (lib/ccwire/frame.ts) against Go
// (vaultchat-backend-go/internal/ccwire/frame.go), through ONE committed fixture
// of hex vectors that both sides assert. Same pattern as the crypto vectors in
// services/crypto/__vectors__ — the file is the contract, and a divergence
// fails a test instead of being discovered on the wire.
//
// The fixture is GENERATED BY GO (`CCWIRE_WRITE_VECTORS=1 go test
// ./internal/ccwire/...`) from literal expectations, and Go's own test fails if
// the committed copy is stale. So:
//   • Go wrote these bytes  → this file proves TS decodes them identically.
//   • These payloads encode → this file proves TS produces the same bytes Go
//     produced, which is the other direction.
//
// STATUS: LIVE. frame.ts is on the app path — client.ts calls encodeFrame on
// every outbound frame and decodeStream on every inbound chunk. Socket.IO is
// gone from the app and the backend.
//
// This header previously read "NOT WIRED, like frame.ts", which was stale in
// the direction that matters: it told the reader these vectors guard nothing.
// Corrected 2026-09-18.

import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  encodeFrame, decodeFrame, decodeStream,
  FRAMING_VERSION, HEADER_BYTES, MAX_FRAME_BYTES,
} from './frame';

const VECTORS = path.join(path.dirname(fileURLToPath(import.meta.url)), '__vectors__', 'frame.json');

let failures = 0;
function check(name: string, ok: boolean, detail?: string): void {
  console.log(`  ${ok ? '✓' : '✗'} ${name}${ok || !detail ? '' : `  (${detail})`}`);
  if (!ok) failures++;
}

const unhex = (s: string): Uint8Array => Uint8Array.from(Buffer.from(s, 'hex'));
const tohex = (b: Uint8Array): string => Buffer.from(b).toString('hex');

console.log('\nCC-Wire v1 Go↔TS parity (shared hex vectors)\n');

if (!fs.existsSync(VECTORS)) {
  console.error(`  ✗ ${VECTORS} is missing.\n` +
    '    Regenerate: cd vaultchat-backend-go && CCWIRE_WRITE_VECTORS=1 go test ./internal/ccwire/...');
  process.exit(1);
}
const v = JSON.parse(fs.readFileSync(VECTORS, 'utf8'));

console.log('Constants agree across languages:');
check('framing version', v.framingVersion === FRAMING_VERSION, `${v.framingVersion} vs ${FRAMING_VERSION}`);
check('header bytes', v.headerBytes === HEADER_BYTES, `${v.headerBytes} vs ${HEADER_BYTES}`);
check('hard max frame bytes', v.maxFrameBytes === MAX_FRAME_BYTES, `${v.maxFrameBytes} vs ${MAX_FRAME_BYTES}`);

console.log('\nTS encodes the bytes Go encoded:');
for (const c of v.encode) {
  const got = tohex(encodeFrame(unhex(c.payloadHex)));
  check(c.name, got === c.frameHex, `got ${got.slice(0, 40)}… want ${c.frameHex.slice(0, 40)}…`);
}

console.log('\nTS decodes Go-generated frames to identical results:');
for (const c of v.decode) {
  const r = decodeFrame(unhex(c.inputHex), {
    maxBytes: c.maxBytes || undefined,
    strict: c.strict,
  });
  if (c.ok) {
    check(c.name,
      r.ok && r.version === c.version && r.consumed === c.consumed && tohex(r.payload) === c.payloadHex,
      r.ok ? `v${r.version} consumed ${r.consumed} payload ${tohex(r.payload)}` : `rejected: ${r.error}`);
  } else {
    check(c.name, !r.ok && r.error === c.error,
      r.ok ? 'ACCEPTED a frame Go refused' : `got ${r.error}, want ${c.error}`);
  }
}

console.log('\nTS stream framing matches Go frame-for-frame:');
for (const c of v.stream) {
  const s = decodeStream(unhex(c.inputHex));
  const wantErr = c.error || undefined;
  const framesMatch =
    s.frames.length === c.framesHex.length &&
    s.frames.every((f, i) => tohex(f) === c.framesHex[i]);
  check(c.name,
    framesMatch && s.consumed === c.consumed && s.error === wantErr,
    `frames=${s.frames.map(tohex).join(',')} consumed=${s.consumed} error=${s.error}`);
}

console.log(failures
  ? `\n  ${failures} FAILED — Go and TypeScript have diverged on the wire format\n`
  : '\n  all CC-Wire Go↔TS parity checks passed\n');
process.exit(failures ? 1 : 0);
