// lib/androidPermissions.selftest.ts - run: npx tsx lib/androidPermissions.selftest.ts
//
// A RUNTIME PERMISSION REQUEST ONLY WORKS IF THE MANIFEST DECLARES IT.
//
// Android does not error on a request for an undeclared permission. It returns
// denied, immediately, WITHOUT SHOWING A DIALOG - indistinguishable in code
// from a user who said no. There is nothing to catch and nothing in a log.
//
// That is how BLUETOOTH_SCAN went missing. lib/items/scanner.ts requested it on
// API 31+ and required every result to be granted, so ensureBlePermissions
// returned false on every Android 12-or-newer device and the whole item-tracker
// feature was dead there. The screen showed "Bluetooth unavailable" and looked
// like a hardware problem.
//
// android/ is gitignored and regenerated by prebuild, so the manifest is NOT
// the source of truth - app.json is, plus the config plugins. This checks
// app.json, and runs the plugin to confirm the flag it adds.

import fs from 'node:fs';

let n = 0;
function ok(what: string, cond: boolean): void {
  if (!cond) { console.error('FAIL: ' + what); process.exit(1); }
  n++;
  console.log('  ok  ' + what);
}

const app = JSON.parse(fs.readFileSync('app.json', 'utf8'));
const declared: string[] = app.expo.android.permissions;

// Every permission this codebase asks for BY NAME at runtime.
const requested = new Set<string>();
for (const f of ['lib/items/scanner.ts', 'lib/games/useTableVoice.ts']) {
  const src = fs.readFileSync(f, 'utf8');
  for (const m of src.matchAll(/'(android\.permission\.[A-Z_]+)'/g)) requested.add(m[1]);
  for (const m of src.matchAll(/PermissionsAndroid\.PERMISSIONS\.([A-Z_]+)/g)) {
    requested.add('android.permission.' + m[1]);
  }
}

ok('found the runtime permission requests to check', requested.size >= 4);
for (const p of [...requested].sort()) {
  ok(`${p} is declared in app.json`, declared.includes(p));
}

// The one that was missing, named explicitly so a silent removal is loud.
ok('BLUETOOTH_SCAN is declared', declared.includes('android.permission.BLUETOOTH_SCAN'));
ok('BLUETOOTH_CONNECT is declared', declared.includes('android.permission.BLUETOOTH_CONNECT'));

// Run the REAL plugin over a manifest shaped like prebuild's output and check
// what comes back, rather than trusting that the code reads correctly.
const plugin = require('../plugins/withAndroidFeatures.js');
const withMods: any = plugin({ name: 'test', slug: 'test' });
const modFn = withMods?.mods?.android?.manifest;
ok('withAndroidFeatures registers an android manifest mod', typeof modFn === 'function');

const manifest = {
  manifest: {
    $: {},
    'uses-permission': [
      { $: { 'android:name': 'android.permission.BLUETOOTH_SCAN' } },
      { $: { 'android:name': 'android.permission.BLUETOOTH_CONNECT' } },
    ],
    'uses-feature': [],
  },
};

(async () => {
  const out: any = await modFn({ ...withMods, modResults: manifest, modRequest: {} } as any);
  const perms: any[] = out.modResults.manifest['uses-permission'];
  const scan = perms.find((x) => x.$['android:name'] === 'android.permission.BLUETOOTH_SCAN');

  ok('the plugin flags BLUETOOTH_SCAN neverForLocation',
     scan?.$['android:usesPermissionFlags'] === 'neverForLocation');
  ok('it does not flag BLUETOOTH_CONNECT',
     perms.find((x) => x.$['android:name'] === 'android.permission.BLUETOOTH_CONNECT')
       ?.$['android:usesPermissionFlags'] === undefined);
  ok('WRITE_CONTACTS is still marked for removal',
     perms.some((x) => x.$['android:name'] === 'android.permission.WRITE_CONTACTS'
                    && x.$['tools:node'] === 'remove'));
  ok('bluetooth hardware stays optional so Play does not filter the install',
     out.modResults.manifest['uses-feature'].some(
       (f: any) => f.$['android:name'] === 'android.hardware.bluetooth_le'
                && f.$['android:required'] === 'false'));

  console.log(`
androidPermissions.selftest: ${n} assertions passed`);
})();
