// lib/buildInputs.selftest.ts - run: npx tsx lib/buildInputs.selftest.ts
//
// A GITIGNORED FILE CANNOT BE A REQUIRED BUILD INPUT.
//
// withTransportCore declares .env.production as an input of the Hermes bundle
// task so that changing a rollout value invalidates the bundle. It used
// inputs.file(), and Gradle FAILS a task whose declared input file is missing.
// .env.production is gitignored, so the one situation that broke was the one
// that matters: a clean clone, or CI, where the file has never existed. The
// release build could not run there at all.
//
// inputs.files() takes a FileCollection, which simply omits a missing entry
// while still re-fingerprinting when the file appears or changes - the cache
// invalidation is preserved, the hard dependency is not.
//
// Both the plugin AND android/app/build.gradle are checked: android/ is
// gitignored and regenerated by prebuild, but the plugin only APPENDS its
// block when absent, so an already-generated tree keeps whatever it has.

import fs from 'node:fs';

let n = 0;
function ok(what: string, cond: boolean): void {
  if (!cond) { console.error('FAIL: ' + what); process.exit(1); }
  n++;
  console.log('  ok  ' + what);
}

const plugin = fs.readFileSync('plugins/withTransportCore.js', 'utf8');
ok('the plugin declares .env.production leniently', plugin.includes('inputs.files(rootProject.files('));
ok('the plugin no longer requires the file to exist', !plugin.includes('inputs.file(rootProject.file('));
ok('the rollout values are still tracked as inputs', plugin.includes('vaultchatTransportRustPct'));

// The generated tree, when one is present - skipped rather than failed, since
// a clean clone legitimately has no android/ until prebuild runs.
const gradle = 'android/app/build.gradle';
if (fs.existsSync(gradle)) {
  const g = fs.readFileSync(gradle, 'utf8');
  if (g.includes('.env.production')) {
    ok('the generated build.gradle matches the plugin', g.includes('inputs.files(rootProject.files('));
    ok('the generated build.gradle has no strict file input', !g.includes('inputs.file(rootProject.file('));
  }
} else {
  console.log('  --  no android/ tree here, nothing generated to check');
}

ok('.env.production is still gitignored', fs.readFileSync('.gitignore', 'utf8').includes('.env.production'));

console.log(`buildInputs.selftest: ${n} assertions passed`);
