// lib/sounds.ts — in-app sound effects + call ringtone (expo-av).
//
// Plays short message tones (sent / received) and a looping call ringtone.
// Preferences (master toggle, chosen ringtone, vibration) persist in
// AsyncStorage. Real bundled WAV tones live in assets/sounds/ — generated by
// scripts, swappable for nicer files anytime.
//
// Note: PUSH (system tray) notification sounds are handled by Android channels
// (see lib/push.ts) — this module is only for sounds while the app is open and
// for the in-app call ringtone.

import { Audio } from 'expo-av';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Vibration, Platform, NativeModules } from 'react-native';
import { SYSTEM_RINGTONE, RINGTONE_PREFS_VERSION, migrateRingtone, resolveRingtone } from './ringtoneChoice';

// Native device-default ringtone (Android) — matches the killed-app ring.
const VaultCalls: any = NativeModules.VaultCalls ?? null;
const nativeRingAvailable = () => Platform.OS === 'android' && !!VaultCalls?.playSystemRingtone;
/** Whether "Phone ringtone" can actually be played here (Android builds with the native module). */
export const systemRingtoneAvailable = nativeRingAvailable;
export { SYSTEM_RINGTONE };

export interface SoundPrefs {
  messageSounds: boolean;   // play sent/received tones while app is open
  ringtone: string;         // SYSTEM_RINGTONE or a ringtone id (see RINGTONES)
  vibrate: boolean;         // vibrate on incoming call
  ringtoneVersion?: number; // see lib/ringtoneChoice migrateRingtone
}
const DEFAULTS: SoundPrefs = { messageSounds: true, ringtone: SYSTEM_RINGTONE, vibrate: true, ringtoneVersion: RINGTONE_PREFS_VERSION };
const KEY = 'vc_sound_prefs';

export const RINGTONES: { id: string; name: string; asset: number }[] = [
  { id: 'ring_pulse',   name: 'Pulse',   asset: require('../assets/sounds/ring_pulse.wav') },
  { id: 'ring_chime',   name: 'Chime',   asset: require('../assets/sounds/ring_chime.wav') },
  { id: 'ring_classic', name: 'Classic', asset: require('../assets/sounds/ring_classic.wav') },
];
const SENT     = require('../assets/sounds/sent.wav');
const RECEIVED = require('../assets/sounds/received.wav');

let prefs: SoundPrefs | null = null;
export async function getSoundPrefs(): Promise<SoundPrefs> {
  if (prefs) return prefs;
  try {
    const raw = await AsyncStorage.getItem(KEY);
    const stored = raw ? JSON.parse(raw) : null;
    prefs = stored
      ? { ...DEFAULTS, ...stored, ringtone: migrateRingtone(stored, 'ring_pulse'), ringtoneVersion: RINGTONE_PREFS_VERSION }
      : { ...DEFAULTS };
  } catch { prefs = { ...DEFAULTS }; }
  return prefs;
}
export async function setSoundPrefs(patch: Partial<SoundPrefs>): Promise<SoundPrefs> {
  const cur = await getSoundPrefs();
  prefs = { ...cur, ...patch };
  try { await AsyncStorage.setItem(KEY, JSON.stringify(prefs)); } catch {}
  return prefs;
}

let audioModeSet = false;
async function ensureAudioMode(): Promise<void> {
  if (audioModeSet) return;
  audioModeSet = true;
  // IMPORTANT: do NOT touch the Android audio mode here. react-native-webrtc
  // manages its own audio session (MODE_IN_COMMUNICATION); calling
  // setAudioModeAsync globally broke call audio. We only set the iOS-only
  // silent-mode flag, which has no effect on the Android call path.
  if (Platform.OS === 'ios') {
    try { await Audio.setAudioModeAsync({ playsInSilentModeIOS: true }); } catch {}
  }
}

// ── Short message tones (preloaded, replayed) ───────────────────
let sentSnd: Audio.Sound | null = null;
let recvSnd: Audio.Sound | null = null;

async function blip(ref: 'sent' | 'recv', asset: number, volume: number): Promise<void> {
  const p = await getSoundPrefs();
  if (!p.messageSounds) return;
  await ensureAudioMode();
  try {
    let snd = ref === 'sent' ? sentSnd : recvSnd;
    if (!snd) {
      const { sound } = await Audio.Sound.createAsync(asset, { volume });
      snd = sound;
      if (ref === 'sent') sentSnd = sound; else recvSnd = sound;
    } else {
      await snd.setPositionAsync(0);
    }
    await snd.replayAsync();
  } catch {}
}
export function playSent():     Promise<void> { return blip('sent', SENT, 0.5); }
export function playReceived(): Promise<void> { return blip('recv', RECEIVED, 0.6); }

// ── Call ringtone (looping) ─────────────────────────────────────
let ringSnd: Audio.Sound | null = null;

export async function startRingtone(): Promise<void> {
  await stopRingtone();
  const p = await getSoundPrefs();
  // The user's pick wins. "Phone ringtone" (the default) plays the device's
  // own ringtone through the native module, which also rings a killed app;
  // without that module (iOS, Expo Go) a bundled tone stands in.
  const plan = resolveRingtone(p.ringtone, nativeRingAvailable(), RINGTONES.map(r => r.id));
  if (plan.kind === 'system') {
    try { VaultCalls.playSystemRingtone(); } catch {}
  } else {
    await ensureAudioMode();
    const rt = RINGTONES.find(r => r.id === plan.id) || RINGTONES[0];
    try {
      const { sound } = await Audio.Sound.createAsync(rt.asset, { isLooping: true, volume: 1.0, shouldPlay: true });
      ringSnd = sound;
    } catch {}
  }
  if (p.vibrate && Platform.OS === 'android') {
    try { Vibration.vibrate([0, 700, 800], true); } catch {}
  }
}
export async function stopRingtone(): Promise<void> {
  try { Vibration.cancel(); } catch {}
  if (nativeRingAvailable()) { try { VaultCalls.stopSystemRingtone(); } catch {} }
  if (ringSnd) {
    const s = ringSnd; ringSnd = null;
    try { await s.stopAsync(); await s.unloadAsync(); } catch {}
  }
}

// ── Preview a ringtone once (settings screen) ───────────────────
// Its own Sound, so leaving the settings screen stops the preview and never
// a real call that is ringing.
let previewSnd: Audio.Sound | null = null;
export async function stopRingtonePreview(): Promise<void> {
  if (!previewSnd) return;
  const s = previewSnd; previewSnd = null;
  try { await s.stopAsync(); await s.unloadAsync(); } catch {}
}
/** Bundled tones only — the phone ringtone is the one the user already knows. */
export async function previewRingtone(id: string): Promise<void> {
  await stopRingtonePreview();
  const rt = RINGTONES.find(r => r.id === id);
  if (!rt) return;
  await ensureAudioMode();
  try {
    const { sound } = await Audio.Sound.createAsync(rt.asset, { volume: 1.0, shouldPlay: true });
    previewSnd = sound;
    sound.setOnPlaybackStatusUpdate((st: any) => {
      if (st?.isLoaded && st.didJustFinish) { sound.unloadAsync().catch(() => {}); if (previewSnd === sound) previewSnd = null; }
    });
  } catch {}
}

export default {};
