// @ts-nocheck
// scripts/build-routing-asset.js — bundle the map-side routing libraries into
// ONE base64 asset the Family/Nav WebView can load offline.
//
// WHY THIS EXISTS: the maps run inside a WebView, and a WebView cannot resolve
// npm packages. Every browser library therefore has to be bundled and embedded,
// exactly as components/nav/maplibreAsset.ts already is. The CDN <script> tags
// in these libraries' READMEs are NOT an option here — the app is required to
// render on no-GMS devices and offline, so nothing may be fetched at runtime.
//
// Run after changing the entry or upgrading any of the libraries:
//   node scripts/build-routing-asset.js
//
// It prints the size, which is the number that matters: this lands in the APK.

const esbuild = require('esbuild');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const entry = path.join(__dirname, 'routing-entry.js');
const out = path.join(root, 'components', 'nav', 'routingAsset.ts');

(async () => {
  const res = await esbuild.build({
    entryPoints: [entry],
    bundle: true,
    format: 'iife',
    platform: 'browser',
    minify: true,
    write: false,
    // maplibre-gl is already loaded in the page from its own embedded asset, so
    // it is ALIASED to a shim that reads window.maplibregl — never `external`.
    // With external + iife, esbuild emits a __require() stub that throws
    // "Dynamic require of maplibre-gl is not supported" and takes the entire
    // bundle down at load, silently. Verified the hard way on a device.
    alias: { 'maplibre-gl': path.join(__dirname, 'maplibre-shim.js') },
    logLevel: 'silent',
  });

  const js = res.outputFiles[0].text;
  const b64 = Buffer.from(js, 'utf8').toString('base64');

  fs.writeFileSync(out, `// GENERATED by scripts/build-routing-asset.js — do not edit by hand.
//
// @any-routing/{core,maplibre-engine,annotation-plugin} + maplibre-pegman,
// bundled for the WebView. Loaded from a data: URL beside the MapLibre asset,
// so the map keeps working with no network and on devices without Play
// Services. Regenerate with:  node scripts/build-routing-asset.js
//
// Raw bundle: ${(js.length / 1024).toFixed(1)} KB → base64 ${(b64.length / 1024).toFixed(1)} KB
export const ROUTING_JS_B64 = '${b64}';
`);

  console.log(`routing bundle: ${(js.length / 1024).toFixed(1)} KB raw, ${(b64.length / 1024).toFixed(1)} KB base64`);
  console.log(`written: ${path.relative(root, out)}`);
})().catch((e) => {
  const errs = (e.errors || []).slice(0, 6)
    .map((x) => `${x.text}${x.location ? ` @ ${x.location.file}:${x.location.line}` : ''}`);
  console.error('BUNDLE FAILED');
  console.error(errs.length ? errs.join('\n') : e.message);
  process.exit(1);
});
